config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'homes#index'

  get '/user-post/:id', to: 'posts#user_posts', as: :user_post
  get 'like/:id', to: 'comments#save_like', as: :like
  get 'comment/:id', to: 'comments#new', as: :new_comment
  post 'comment/:id', to: 'comments#create', as: :comments

  get 'friends/:id', to: 'friends#friends', as: :friends
  get 'pending-friends/:id', to: 'friends#pending_friends', as: :pending_friends
  get 'request-friendship/:id', to: 'friends#create', as: :request_friend
  get 'friend-requests', to: 'friends#friend_requests', as: :friend_request
  get 'accept-friendship/:id', to: 'friends#accept_friend', as: :accept_friend

  devise_for :users, skip: [:sessions], controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
    get 'signup', to: 'devise/registrations#new', as: :new_user
  end

  resources :posts
  resources :users, only: [:index, :show]
end

app/controllers/friends_controller.rb
# frozen_string_literal: true

class FriendsController < ApplicationController
  before_action :find_user, only: %i[create friends pending_friends accept_friend]
  def create
    friendship = current_user.friendships.create
    friendship.friend_id = @user.id
    if friendship.save
      flash[:success] = "Friendship sent successfully to #{@user.first_name} "
    else
      flash[:danger] = 'Something went wrong '
    end

    redirect_to users_path
  end

  def friends
    @friends = @user.friends
  end

  def pending_friends
    @friends = @user.pending_friends

    render 'friends'
  end

  def friend_requests
    @friends = current_user.friend_requests
  end

  def accept_friend
    if current_user.comfirm_friend(@user)
      flash[:success] = "Friendship confirmed successfully from #{@user.first_name} "
    else
      flash[:danger] = 'Something went wrong '
    end

    redirect_to friend_request_path
  end

  private

  def find_user
    @user = User.friendly.find(params[:id])
  end
end

app/helpers/friends_helper.rb
# frozen_string_literal: true

module FriendsHelper
end

app/views/friends/_find_friends.html.erb
<div class="center">
  Follow the link to find and connect with more friends
  <%= link_to 'find friends', users_path, class: 'btn btn-primary rounded-o'%>
</div>

app/views/friends/_friends.html.erb
<%= gravatar_for friend, 50 %>
<b><%= link_to name(friend), friend %></b>
<p><%= friend.address %></p>

app/views/friends/friend_requests.html.erb
<div class="mt-5">
  <%= render "layouts/flash_message" %>
  <% if !@friends.blank? %>
  <% @friends.each do |friend| %>
  <div class="card mt-4">
    <div class="card-body">
      <div>
        <%= gravatar_for friend, 50 %>
        <b><%= link_to name(friend), friend %></b>
        <p><%= friend.address %></p>
        <%= link_to 'Accept Friendship', accept_friend_path(friend), class: 'btn btn-success rounded-0'%>
      </div>
    </div>
  </div>
  <%end%>
  <% else %>
  <%= render 'friends/find_friends'%>
  <%end%>
</div>

app/views/friends/friends.html.erb
<div class="mt-5">
  <% if !@friends.blank? %>
  <% @friends.each do |friend| %>
  <div class="card mt-4">
    <div class="card-body">
      <div>
        <%= gravatar_for friend, 50 %>
        <b><%= link_to name(friend), friend %></b>
        <p><%= friend.address %></p>
      </div>
    </div>
  </div>
  <%end%>
  <% else %>
  <%= render 'friends/find_friends'%>
  <%end%>
</div>