config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'homes#index'

  get '/user-post/:id', to: 'posts#user_posts', as: :user_post
  get 'like/:id', to: 'comments#save_like', as: :like
  get 'comment/:id', to: 'comments#new', as: :new_comment
  post 'comment/:id', to: 'comments#create', as: :comments

  get 'friends/:id', to: 'friends#friends', as: :friends
  get 'pending-friends/:id', to: 'friends#pending_friends', as: :pending_friends
  get 'request-friendship/:id', to: 'friends#create', as: :request_friend
  get 'friend-requests', to: 'friends#friend_requests', as: :friend_request
  get 'accept-friendship/:id', to: 'friends#accept_friend', as: :accept_friend

  devise_for :users, skip: [:sessions], controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
    get 'signup', to: 'devise/registrations#new', as: :new_user
  end

  resources :posts
  resources :users, only: [:index, :show]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: [:facebook]

  validates :first_name, presence: true
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :friendships
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'

  def name
    [
      %i[first_name last_name]
    ]
  end

  scope :all_except, ->(user) { where.not(id: user) }

  def friends
    friends_array = []
    friendships.each { |friendship| friends_array << friendship.friend if friendship.comfirmed }
    inverse_friendships.each { |friendship| friends_array << friendship.user if friendship.comfirmed }
    friends_array.compact
  end

  def comfirm_friend(user)
    friendship = inverse_friendships.find { |friend| friend.user == user }
    friendship.comfirmed = true
    friendship.save
  end

  def friend?(user)
    friends.include?(user)
  end

  def pending_friends
    friendships.map { |friendship| friendship.friend unless friendship.comfirmed }.compact
  end

  def friend_requests
    inverse_friendships.map { |friendship| friendship.user unless friendship.comfirmed }.compact
  end

  def pending_friend?(user)
    pending_friends.include?(user)
  end

  def potential_friends(current_user)
    User.all.map { |user| user unless friend?(user) || current_user == user }.compact
  end

  def self.from_omniauth(auth)
    password = Devise.friendly_token[0, 20]
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = password
      user.password_confirmation = password
      user.first_name = auth.info.name
      user.last_name = ' '
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = current_user.potential_friends(current_user)
  end

  def show
    @user = User.friendly.find(params[:id])
  end

  def edit; end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def my_profile(user)
    return true if current_user == user

    false
  end
end

app/views/users/index.html.erb

<div class="mt-5">
  <%= render "layouts/flash_message" %>
  <% if !@users.blank? %>
  <% @users.each do |user| %>
  <div class="card mt-4">
    <div class="card-body">
      <div>
        <%= gravatar_for user, 50 %>
        <b><%= link_to name(user), user %></b>
        <p><%= user.address %></p>
        <% if current_user.friend?(user)%>
        <p>You are friends</p>
        <% elsif current_user.pending_friend? user%>
        <button class="btn-primary">Pending Request</button>
        <% else%>
        <%= link_to 'Request Friendship', request_friend_path(user), class: 'btn btn-success rounded-0'%>
        <% end%>
      </div>
    </div>
  </div>
  <%end%>
  <% else %>
    <%= render 'friends/find_friends' %>
  <%end%>
</div>

app/views/users/show.html.erb
<div class="card start-feed">
  <%= render 'share/feed_icon'%>
</div>
<div class="card mt-4">
  <div class="card-body">
    <div class="card-flex">
      <div><%= gravatar_for @user , 100 %></div>
      <div class="user-header">
        <p class="user-detail"><%= name(@user)%></p>
        <p class="user-detail"><%= @user.email%></p>
        <p class="user-detail">Joined <%= time_ago_in_words(@user.created_at) %> ago</p>
        <p class="user-detail">Friends: <%= @user.friends.count %></p>
      </div>
    </div>
  </div>
  <div class="card-footer text-muted">
    <div>
      <%= link_to 'posts', user_post_path, class: 'btn btn-success rounded-0'%>
      <%= link_to 'friends', friends_path, class: 'btn btn-success rounded-0'%>
      <% if my_profile @user%>
      <%= link_to 'pending friends', pending_friends_path, class: 'btn btn-success rounded-0'%>
      <% elsif current_user.friend?(@user)%>
      <p>You are friends</p>
      <% elsif current_user.pending_friend? @user%>
      <button class="btn-primary">Pending Request</button>
      <% else%>
      <%= link_to 'Request Friendship', request_friend_path(@user), class: 'btn btn-success rounded-0'%>
      <% end%>
    </div>
  </div>
</div>