config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'homes#index'

  get '/user-post/:id', to: 'posts#user_posts', as: :user_post
  get 'like/:id', to: 'comments#save_like', as: :like
  get 'comment/:id', to: 'comments#new', as: :new_comment
  post 'comment/:id', to: 'comments#create', as: :comments

  get 'friends/:id', to: 'friends#friends', as: :friends
  get 'pending-friends/:id', to: 'friends#pending_friends', as: :pending_friends
  get 'request-friendship/:id', to: 'friends#create', as: :request_friend
  get 'friend-requests', to: 'friends#friend_requests', as: :friend_request
  get 'accept-friendship/:id', to: 'friends#accept_friend', as: :accept_friend

  devise_for :users, skip: [:sessions], controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
    get 'signup', to: 'devise/registrations#new', as: :new_user
  end

  resources :posts
  resources :users, only: [:index, :show]
end

app/views/layouts/_feeds_icons.html.erb
<div class="card-body start-feed-content">
  <div>
    <a <i class="fa fa-pencil"> <%= link_to "start a post", new_post_path %> </i></a>
  </div>
  <div>
    <a <i class="fa fa-camera"> <%= link_to "upload an image", new_post_path %> </i> </a>
  </div>
  <div>
    <a href="#"> <i class="fa fa-newspaper-o"> </i></a>
  </div>
</div>

app/views/layouts/_flash_message.html.erb
<% flash.each do |key, value| %>
	<% key = "success" if key == "success" %>
	<% key = "danger" if key == "danger" %>
  <div class="alert alert-<%= key %>">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong><%= value %></strong>
  </div>        
<% end %>

app/views/layouts/_footer.html.erb
<div class="mt-5">

</div>

app/views/layouts/_friend_request.html.erb
<% if current_user.friend?(user)%>
<p>You are friends</p>
<% elsif current_user.pending_friend? user%>
<button class="btn-primary">Pending Request</button>
<% else%>
<%= link_to 'Request Friendship', request_friend_path(user), class: 'btn btn-success rounded-0'%>
<% end%>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg custom-navbar">
  <div class="container"> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" <%= link_to "Facebook", root_path %> </a>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" <%= link_to "Home", root_path %> </a> <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Feeds", posts_path %> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "New Post", new_post_path %> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Make Friends", users_path %> </a>
        </li>
        <li class="nav-item">
          <% if current_user%>
          <%= gravatar_for current_user%>
          <% end%>
        </li>
        <% if current_user && current_user.friend_requests %>
        <li class="nav-item">
           <%= link_to " ", friend_request_path , class: 'fa fa-bell ml-2 mt-2', style: 'color: white'%>
           <b style="color:white"><%= current_user.friend_requests.count%></b>
        </li>
        <% end %>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <% if current_user%>
      <a class="nav-link" <%= link_to "Log out", destroy_user_session_path, method: :delete %></a>
      <% else %>
      <a class="nav-link" <%= link_to "Sign up", new_user_path %></a>
      <a class="nav-link" <%= link_to "Sign in", new_user_session_path %></a>
      <% end%>
    </div>
  </div>
</nav>

app/views/layouts/_posts.html.erb
<div class="mt-4">
  <% if !@posts.blank? %>
<% @posts.each do |post| %>
<div class="card mt-3">
  <div class="card-header">
    <div class="card-flex">
      <div><%= gravatar_for post.user , 40 %></div>
      <div class="post-header">
        <p class="post-header-detail"><%= link_to post_owner(post), post.user%></p>
        <p class="post-header-detail"><%= post.user.email%></p>
        <p class="post-header-detail"><%= time_ago_in_words(post.created_at) %> ago</p>
      </div>
    </div>
  </div>
  <div class="card-body">
    <p class="card-text"><%= link_to truncate(post.description), post %></p>
    <% if post.image %>
    <div class="img-div"><%= image_tag post.image, width:"500px", class:"img-fluid" if post.image.attached?%></div>
    <%end%>
  </div>
  <div class="card-footer text-muted like-and-comments">
    <%= link_to ' ', like_path(post), class: 'like fa fa-thumbs-up' %>
    <i><%= post.likes.count %></i>
    <%= link_to 'comments', new_comment_path(post)%>
  </div>
</div>
<%end%>
<% else %>
Nothing Here
<%end%>
</div>

app/views/layouts/_sidenav.html.erb
<div class="card profile">
  <div class="card-body">
    <%= gravatar_for current_user, 70 %>
    <h6 class="card-title mt-3"><%= name%></h6>
    <p class="card-text"><%= current_user.email%></p>
    <p class="card-text"><%= current_user.address%></p>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Facebok</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body class="body">
  <%= render 'layouts/nav' %>
  <% if current_user%>
  <div class="container mt-4">
    <div class="row">
      <div class="col-md-3">
        <div class="card profile">
          <div class="card-body">
            <%= gravatar_for current_user, 70 %>
            <h6 class="card-title mt-3"><%= link_to name, current_user%></h6>
            <p class="card-text"><%= current_user.email%></p>
            <p class="card-text"><%= current_user.address%></p>
            <p class="card-text">Friends: <%= current_user.friends.count%></p>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <%= yield %>
      </div>
      <div class="col-md-3">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">Ads here</h5>
            <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
              content.</p>
            <a href="#" class="card-link">Card link</a>
            <a href="#" class="card-link">Another link</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= render 'layouts/footer' %>
  <% else%>
  <%= yield%>
  <%end%>

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
</body>

</html>

</body>

</html>